import {cases,runCase,money,validateFacts,toCSV} from './domain.js';

let caseId='capacity',pageName='Overview',threshold=5,round=1,run=runCase(cases[0]),message='';
let core,appContainer,sideNav,navBox,runButton;
const navDefs=[['Overview','home'],['Data Workspace','database'],['Conflict Detector','alert'],['Agent Review','collaborate'],['Consensus Room','discussion-2'],['Executive Pack','document-text'],['Audit Trail','history'],['Settings','action-settings']];
const byPage={};
const text=(s,cls)=>new sap.m.Text({text:String(s??''),wrapping:true}).addStyleClass(cls||'');
const label=(s)=>new sap.m.Label({text:s});
const title=(s,level='H3')=>new sap.m.Title({text:s,level});
const status=(s,state='None')=>new sap.m.ObjectStatus({text:s,state});
const small=(s)=>text(s,'sapUiSmallMarginTop sapUiTinyMarginBottom');
const gap=(items,cls='')=>new sap.m.VBox({items,renderType:'Bare'}).addStyleClass(cls);
const row=(items,cls='')=>new sap.m.HBox({items,alignItems:'Center',justifyContent:'SpaceBetween',wrap:'Wrap'}).addStyleClass(cls);
function panel(head,sub,items){const p=new sap.m.Panel({headerText:head,expandable:false,content:Array.isArray(items)?items:[items]});if(sub)p.setHeaderToolbar(new sap.m.Toolbar({content:[new sap.m.Title({text:head,level:'H4'}),new sap.m.ToolbarSpacer(),new sap.m.Text({text:sub})]}));p.addStyleClass('sapUiSmallMarginBottom');return p}
function grid(items,span='XL6 L6 M12 S12'){return new sap.ui.layout.Grid({defaultSpan:span,hSpacing:1,vSpacing:1,content:items})}
function metricTile(name,value,detail,icon,state='None'){return new sap.m.GenericTile({header:name,subheader:detail,frameType:'OneByHalf',tileContent:[new sap.m.TileContent({unit:'',content:new sap.m.NumericContent({value:String(value),icon,indicator:'None',valueColor:state==='Error'?'Error':state==='Critical'?'Critical':'Neutral'})})]}).addStyleClass('sapUiTinyMarginEnd sapUiTinyMarginBottom')}
function table(headers,rows,onPress){const t=new sap.m.Table({mode:'None',inset:false,alternateRowColors:true});headers.forEach(h=>t.addColumn(new sap.m.Column({header:label(h)})));rows.forEach(cells=>{const item=new sap.m.ColumnListItem({type:onPress?'Navigation':'Inactive',cells:cells.map(c=>typeof c==='string'?text(c):c)});if(onPress)item.attachPress(()=>onPress());t.addItem(item)});return t}
function caseSelect(){return new sap.m.Select({selectedKey:caseId,width:'22rem',items:cases.map(c=>new sap.ui.core.Item({key:c.id,text:c.name})),change:e=>{caseId=e.getSource().getSelectedKey();run=runCase(cases.find(c=>c.id===caseId),threshold);message='Scenario loaded.';renderPage()}})}
function runNow(){run=runCase(cases.find(c=>c.id===caseId),threshold);round=1;message='Analysis complete. Deterministic issue detection and both bounded agent rounds are recorded.';renderPage()}
function pageHeader(name){const c=cases.find(x=>x.id===caseId);return new sap.m.VBox({items:[row([title(name,'H2'),new sap.m.Button({text:'Run analysis',icon:'sap-icon://begin',type:'Emphasized',press:runNow})]),text(`S&OP cycle · Reconciliation review (2BU) · ${c.name}`,'sapUiTinyMarginBottom'),message?new sap.m.MessageStrip({text:message,type:'Success',showIcon:true,showCloseButton:true,close:()=>{message='';renderPage()}}):null].filter(Boolean)}).addStyleClass('sapUiSmallMarginBottom')}
function page(name,content){return new sap.m.Page({title:name,enableScrolling:true,content:[new sap.m.VBox({items:[pageHeader(name),...content],width:'100%'}).addStyleClass('sapUiResponsiveContentPadding')]})}
function overview(){const d=run.decisions[0];const issues=run.issues;const kpis=new sap.m.HBox({wrap:'Wrap',items:[metricTile('Material conflicts',issues.length,'Deterministically identified','sap-icon://alert','Critical'),metricTile('Revenue at risk',money(issues.reduce((a,i)=>a+i.revenueDelta,0)),'Consensus vs. constrained','sap-icon://money-bills','Error'),metricTile('Capacity hotspots',issues.filter(i=>i.overCapacity).length,'Utilization above 100%','sap-icon://factory','Critical'),metricTile('Open decisions',run.decisions.filter(x=>x.status!=='converged').length,'Requires owner review','sap-icon://discussion-2','Critical')]});
const issueRows=issues.map(i=>[text(i.id+' · '+i.fact.product),text(i.fact.location+' · '+i.fact.period),new sap.m.ObjectNumber({number:money(i.revenueDelta),state:'Error'}),new sap.m.ProgressIndicator({percentValue:Math.min(i.fact.capacityUtilization*100,100),displayValue:`${Math.round(i.fact.capacityUtilization*100)}%`,state:i.overCapacity?'Warning':'Success'}),status(`${i.materiality}/100`),status(d?.status||'Run analysis','Warning')]);
const health=new sap.m.List({items:[['2BQ','Demand review','Complete'],['2BS','Supply review','Complete'],['2BU','Reconciliation','In progress'],['2BW','Management review','Upcoming']].map((x,i)=>new sap.m.StandardListItem({title:x[1],description:x[0]+' · '+x[2],icon:i<2?'sap-icon://accept':'sap-icon://process',info:x[2],infoState:i===2?'Information':'Success'}))});
return [row([label('Active scenario'),caseSelect(),new sap.m.ToolbarSpacer(),status('Synthetic demo data','Information'),text('Cycle 2026-W42 · Review 2BU')],'sapUiSmallMarginBottom'),kpis,panel('Reconciliation priorities','Ranked by transparent business materiality',table(['Issue / Product','Location · Period','Revenue delta','Capacity','Materiality','Status'],issueRows,()=>go('Conflict Detector'))),grid([panel('S&OP cycle health','Current reconciliation cycle',[health,text('Last analysis: '+new Date(run.createdAt).toLocaleTimeString())]),panel('Consensus snapshot','Coordinator synthesis',[status(d?.status||'Run analysis','Warning'),text(d?.proposal||'Run analysis to create a reconciliation brief.','sapUiSmallMarginTop'),text('Final decision remains with the human S&OP owner.'),new sap.m.Button({text:'Open Consensus Room',icon:'sap-icon://discussion-2',press:()=>go('Consensus Room')})])])];}
function dataWorkspace(){const cards=cases.map(c=>new sap.m.CustomListItem({content:[row([new sap.m.VBox({items:[title(c.name,'H5'),text(c.description),status(`Synthetic · ${c.facts.length} fact row${c.facts.length===1?'':'s'}`)]}),new sap.m.Button({text:'Load scenario',icon:'sap-icon://open-folder',press:()=>{caseId=c.id;run=runCase(c,threshold);message='Scenario loaded.';go('Overview')}})])]}));const uploader=new sap.ui.unified.FileUploader({buttonOnly:false,buttonText:'Choose CSV extract',fileType:['csv'],change:onUpload,width:'100%'});return [grid([panel('Planning data source','Choose a demo scenario or import a planning extract',[new sap.m.List({items:cards}),new sap.m.Label({text:'Customer-authorized CSV planning extract'}),uploader,text('Required fields: product, location, customer, period, consensusDemand, constrainedDemand, receipts, consensusRevenue, constrainedRevenue, aop, capacityUtilization.'),status('Uploaded file text is validated and treated only as data.','Information')]),panel('Connection status','Provider configuration',[row([new sap.ui.core.Icon({src:'sap-icon://connected',color:'#188918',size:'1.25rem'}),title('DemoProvider · Active','H5')]),text('Live SAP tenant access is disabled. SAP read adapters remain extension points; no credentials are stored or requested.'),new sap.m.Button({text:'Adapter settings',press:()=>go('Settings')})])])];}
function conflicts(){const slider=new sap.m.Slider({min:1,max:25,value:threshold,width:'20rem',liveChange:e=>{threshold=e.getParameter('value');thresholdLabel.setText(`${threshold}%`)}});const thresholdLabel=text(`${threshold}%`);const controls=row([label('Revenue materiality threshold'),slider,thresholdLabel,new sap.m.Button({text:'Recalculate',type:'Emphasized',press:()=>{run=runCase(cases.find(c=>c.id===caseId),threshold);message='Materiality recalculated.';renderPage()}})]).addStyleClass('sapUiSmallMarginBottom');const issuePanels=run.issues.map(i=>panel(`${i.id} · ${i.fact.product} · ${i.fact.location} · ${i.fact.period}`,`${i.materiality}/100 materiality`,[table(['Metric','Source fact'],[['Consensus demand',i.fact.consensusDemand.toLocaleString()+' units'],['Constrained demand',i.fact.constrainedDemand.toLocaleString()+' units'],['Demand gap',i.demandGap.toLocaleString()+' units'],['Consensus revenue',money(i.fact.consensusRevenue)],['Constrained revenue',money(i.fact.constrainedRevenue)],['Revenue delta',money(i.revenueDelta)],['AOP target',money(i.fact.aop)],['Capacity utilization',Math.round(i.fact.capacityUtilization*100)+'%'],['Margin',Math.round(i.fact.margin*100)+'%']]),text('Score: min(100, 2 × |revenue delta %| + 30 for capacity >100% + 15 for commitment + 12 for margin <20%).')]));return [panel('Detected material issues','Round 0 · Deterministic calculations before agent review',[text('Adjust the transparent materiality rule, then recalculate.'),controls,...issuePanels]),panel('Materiality rules','Transparent and adjustable',[table(['Rule','Current threshold'],[['Revenue delta',`≥ ${threshold}%`],['Over-capacity','> 100% utilization'],['Customer commitment','Flagged in source facts']])])];}
function positionCard(p){return panel(`${p.agent} Agent`,`${p.stance.toUpperCase()} · Confidence ${Math.round(p.confidence*100)}%`,[text(p.summary),new sap.m.Label({text:'Trade-off'}),text(p.tradeoff),new sap.m.Label({text:'Evidence references'}),new sap.m.FlexBox({wrap:'Wrap',items:p.evidenceRefs.map(x=>status(x,'Information'))}),p.missingData.length?new sap.m.MessageStrip({text:'Missing evidence: '+p.missingData.join(' · '),type:'Warning',showIcon:true}):null].filter(Boolean))}
function agentReview(){const issue=run.issues[0];const ps=(round===1?run.round1:run.round2).filter(p=>p.issueId===issue?.id);const rounds=new sap.m.SegmentedButton({selectedKey:String(round),items:[new sap.m.SegmentedButtonItem({key:'1',text:'Round 1 · Independent'}),new sap.m.SegmentedButtonItem({key:'2',text:'Round 2 · Confrontation'})],selectionChange:e=>{round=Number(e.getParameter('item').getKey());renderPage()}});return [panel('Bounded negotiation protocol','Same issue facts · Evidence-linked functional positions',[text('Functional positions are generated in two bounded rounds. No free-form agent-to-agent chat.'),rounds]),new sap.m.VBox({items:ps.map(positionCard)}),!ps.length?new sap.m.MessageStrip({text:'Run analysis to generate evidence-linked positions.',type:'Information',showIcon:true}):null].filter(Boolean)}
function consensus(){const i=run.issues[0],d=run.decisions[0];if(!d)return [new sap.m.MessageStrip({text:'Run analysis to build a coordinator synthesis.',type:'Information',showIcon:true})];const approval=new sap.m.CheckBox({text:'I reviewed this proposal (local demo record)',selected:!!run.approved,select:e=>{run={...run,approved:e.getParameter('selected'),audit:[...run.audit,e.getParameter('selected')?'Human marked proposal reviewed (local demo).':'Human review mark removed (local demo).']};renderPage()}});return [panel('Coordinator synthesis','Calculated source facts and agent positions',[status(d.status,'Warning'),title(d.proposal,'H4'),text(d.reason),new sap.m.MessageStrip({text:'Decision required from the S&OP owner. This demo does not write to SAP.',type:'Warning',showIcon:true})]),panel('Owner decision','Review the trade-off',[title(`${i.fact.product} · ${i.fact.customer} · ${i.fact.period}`,'H5'),grid([panel('Solution 1 · Protect customer service','Candidate only',[text('Validate alternate supply; may add expedite cost or displace another segment.')]),panel('Solution 2 · Protect feasibility','Candidate only',[text('Retain the constrained plan; consensus demand and AOP may be missed.')])]),approval,status('No SAP write-back','Information')]),panel('Evidence coverage','Source facts and metric references',text(`${run.round2.reduce((n,p)=>n+p.evidenceRefs.length,0)} evidence links are attached to the agent positions.`))];}
function executive(){const c=cases.find(x=>x.id===caseId),d=run.decisions[0];return [panel('Executive reconciliation pack · 2BW','Draft for human review',[row([status('Demo · Synthetic source','Information'),text(new Date(run.createdAt).toLocaleString())]),title(c.name,'H3'),text(c.description),table(['Issue','Product · Location','Demand gap','Revenue delta','Capacity','Recommendation'],run.issues.map(i=>[i.id,`${i.fact.product} · ${i.fact.location}`,i.demandGap.toLocaleString(),money(i.revenueDelta),Math.round(i.fact.capacityUtilization*100)+'%',d?.proposal||'Run analysis first.'])),new sap.m.Button({text:'Export executive pack (JSON)',icon:'sap-icon://download',type:'Emphasized',press:()=>download(`${run.runId}-executive-pack.json`,{product:'Cognto S&OP Consensus Agent',disclosure:'Demo / No SAP Write-Back',run})}),new sap.m.Button({text:'Export issue facts (CSV)',icon:'sap-icon://excel-attachment',press:()=>download(`${run.runId}-issues.csv`,toCSV(run.issues),'text/csv')})]),panel('Human approval gate','Decision posture',[status(run.approved?'Reviewed locally':'Awaiting human review',run.approved?'Success':'Warning'),text('Exporting records a draft package; no SAP write-back occurs.')])];}
function audit(){return [grid([panel('Run audit','Append-only events for this local run',[table(['Run detail','Value'],[['Run ID',run.runId],['Scenario',cases.find(x=>x.id===caseId).name],['Created',new Date(run.createdAt).toLocaleString()],['Approval',run.approved?'Reviewed locally':'Not reviewed']]),new sap.m.List({items:run.audit.map((x,i)=>new sap.m.StandardListItem({title:x,description:i===0?'Source facts · synthetic':i<4?'Orchestration · deterministic demo':'Human review · local only',icon:'sap-icon://history'}))}),new sap.m.Button({text:'Export audit JSON',icon:'sap-icon://download',press:()=>download(`${run.runId}-audit.json`,{run})})]),panel('Evidence integrity','Run package',[text('Issue facts, both agent rounds, coordinator classification and review status are included in the export.'),status('Evidence references retained','Success')])])];}
function settings(){const inp=new sap.m.Input({type:'Number',value:String(threshold),min:1,max:25,width:'8rem',change:e=>{threshold=Math.max(1,Math.min(25,Number(e.getParameter('value'))||5))}});return [grid([panel('Run settings','Local demonstration configuration',[new sap.ui.layout.form.SimpleForm({editable:true,layout:'ResponsiveGridLayout',content:[label('Revenue materiality threshold (%)'),inp,label('Currency'),new sap.m.Select({selectedKey:'USD',items:[new sap.ui.core.Item({key:'USD',text:'USD · US Dollar'})]}),label('Agent provider'),new sap.m.Select({selectedKey:'mock',items:[new sap.ui.core.Item({key:'mock',text:'Deterministic demo provider'}),new sap.ui.core.Item({key:'llm',text:'External LLM · server provider required',enabled:false})]}),label('SAP IBP provider'),new sap.m.Select({selectedKey:'demo',items:[new sap.ui.core.Item({key:'demo',text:'DemoProvider · active'}),new sap.ui.core.Item({key:'odata',text:'Extract OData · extension point',enabled:false}),new sap.ui.core.Item({key:'api',text:'Planning Data API · extension point',enabled:false})]})]}),new sap.m.MessageStrip({text:'Production SAP calls are disabled. No credentials or tokens are embedded in this demo.',type:'Information',showIcon:true})]),panel('Governance policy','Read-only demo',[new sap.m.List({items:['No SAP write-back','Numeric comparisons are deterministic','All agent positions carry evidence references','Human decision owns final outcome','Uploaded text is treated as data'].map(x=>new sap.m.StandardListItem({title:x,icon:'sap-icon://accept'}))})])])];}
function download(name,data,type='application/json'){const blob=new Blob([type==='text/csv'?data:JSON.stringify(data,null,2)],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function onUpload(e){const f=e.getParameter('files')?.[0]||e.getSource().oFileUpload.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{const lines=String(reader.result).trim().split(/\r?\n/),keys=lines[0].split(',').map(x=>x.trim()),rows=lines.slice(1).map(l=>l.split(',').map(x=>x.trim())).map(cols=>Object.fromEntries(keys.map((k,i)=>[k,cols[i]??'']))),result=validateFacts(rows);if(result.errors.length){message=`Schema validation found ${result.errors.length} issue(s): ${result.errors.slice(0,4).join(' ')}`;go('Data Workspace');return}run=runCase({...cases.find(x=>x.id===caseId),facts:result.facts},threshold);message=`Loaded ${result.facts.length} planning fact row(s). Uploaded text is treated only as data.`;go('Conflict Detector')};reader.readAsText(f)}
function go(n){pageName=n;const item=sideNav.getItems().find(i=>i.data('route')===n);if(item)sideNav.setSelectedItem(item);if(byPage[n])appContainer.to(byPage[n]);else renderPage()}
function renderPage(){if(!appContainer)return;const fns={'Overview':overview,'Data Workspace':dataWorkspace,'Conflict Detector':conflicts,'Agent Review':agentReview,'Consensus Room':consensus,'Executive Pack':executive,'Audit Trail':audit,'Settings':settings};const old=byPage[pageName];if(old){appContainer.removePage(old);old.destroy()}const next=page(pageName,fns[pageName]());byPage[pageName]=next;appContainer.addPage(next);appContainer.to(next);}
function init(){const bar=new sap.m.Bar({design:sap.m.BarDesign.Header,contentLeft:[new sap.m.Button({icon:'sap-icon://menu2',type:'Transparent',tooltip:'Toggle navigation',press:()=>navBox.setVisible(!navBox.getVisible())}),new sap.m.Title({text:'Cognto',level:'H4'})],contentMiddle:[new sap.m.Text({text:'S&OP Consensus Agent'})],contentRight:[new sap.m.ObjectStatus({text:'Demo · No SAP write-back',state:'Warning'})]});const msg=new sap.m.MessageStrip({text:'Demo mode · Synthetic planning data · SAP connection disabled · Human approval required for decisions',type:'Information',showIcon:true});sideNav=new sap.m.List({mode:'SingleSelectMaster',includeItemInSelection:true,selectionChange:e=>{const item=e.getParameter('listItem');go(item.data('route'))},items:navDefs.map(([name,icon])=>new sap.m.StandardListItem({title:name,icon:'sap-icon://'+icon,type:'Active',selected:name==='Overview'}).data('route',name))});sideNav.addStyleClass('sopSideNav');navBox=new sap.m.VBox({width:'220px',height:'100%',items:[sideNav]});navBox.setLayoutData(new sap.m.FlexItemData({shrinkFactor:0}));appContainer=new sap.m.App({height:'100%'});appContainer.setLayoutData(new sap.m.FlexItemData({growFactor:1,shrinkFactor:1}));const body=new sap.m.HBox({fitContainer:true,alignItems:'Stretch',items:[navBox,appContainer]});body.setLayoutData(new sap.m.FlexItemData({growFactor:1,shrinkFactor:1}));const root=new sap.m.VBox({height:'100%',fitContainer:true,items:[bar,msg,body]});root.addStyleClass('sopAppShell');root.placeAt('app');go('Overview');}
if(window.sap?.ui?.getCore)window.sap.ui.getCore().attachInit(init);else document.getElementById('sap-ui-bootstrap')?.addEventListener('load',()=>sap.ui.getCore().attachInit(init));
